export const decks = {
  A: [
    "Peregrine Falcon",
    "Giant UFO",
    "Coral Snake",
    "Forbidden Arts",
    "Anaconda",
    "Ice Meteor (Bronze)",
    "Soul of a King",
    "Rattlesnake",
    "Alien Egg B",
    "Snow Leopard",
    "Hidden Strength",
    "African Elephant (Silver)",
    "Great Horned Owl",
    "Volcanic Chain",
    "African Wild Dog",
    "Unbreakable Spirit",
    "Cheetah",
    "Giant Melon",
    "Leo the Lion Cub (Bronze)",
    "Lightning",
    "Leopard",
    "Burning Spirit",
    "Indian Gavial",
    "Smalltooth Sawfish",
    "Alien Egg C",
    "Goblin Shark",
    "Black Panther",
    "Ultimate Power",
    "Golden Eagle",
    "Electric Ray",
    "Victory Power (Bronze)",
    "Lightning Speed",
    "Super Lightning",
    "Brown Bear",
    "Asiatic Black Bear",
    "Giant Meteor (Bronze)",
    "Turnaround Blow",
    "Manta Ray",
    "Giant Melon",
    "Andean Condor",
    "Pure Soul",
    "Giant Panda (Bronze)",
    "Volcanic Chain",
    "Side Striped Jackal",
    "Sawshark",
    "Hidden Strength",
    "Peregrine Falcon",
    "Fissure",
    "Coral Snake",
    "Earthquake",
    "Anaconda",
    "Giant UFO",
    "Rattlesnake",
    "Focus Charge",
    "Icarus the Young Eagle (Bronze)",
    "Insatiable Appetite",
    "Alien Egg B",
    "Snow Leopard",
    "Great Horned Owl",
    "Time of Miracles",
    "African Wild Dog",
    "Alien Egg C",
    "Hidden Power (Bronze)",
    "Anaconda",
    "Cheetah",
    "Lightning Speed",
    "Leopard",
    "Lava Flow",
    "Meteor Shower (Silver)",
    "Indian Gavial",
    "Decisive Strike",
    "Smalltooth Sawfish",
    "Lightning",
    "Nile Crocodile (Bronze)",
    "Ultimate Power",
    "Goblin Shark",
    "Nasty Surprise",
    "Black Panther",
    "Golden Eagle",
    "Insatiable Appetite",
    "Electric Ray",
    "Super Lightning",
    "Leadership (Bronze)",
    "Brown Bear",
    "Earthquake",
    "Asiatic Black Bear",
    "Lion (Gold)",
    "Manta Ray",
    "Call of the Wild",
    "Andean Condor",
    "Magma Inferno",
    "Side Striped Jackal",
    "Alien Egg A (Bronze)",
    "All Out Power",
    "Sawshark",
    "Furious Charge",
    "Great Lightning",
    "Peregrine Falcon",
    "Giant Melon",
    "Shining Blade",
    "Soul of a King",
    "Coral Snake",
    "Great Lightning",
    "Anaconda",
    "Arctic Training (Bronze)",
    "Furious Charge",
    "Rattlesnake",
    "Super Lightning",
    "Snow Leopard",
    "Early Riser",
    "Great Horned Owl",
    "Volcanic Chain",
    "Ocean Power (Silver)",
    "African Wild Dog",
    "Wheels of Fate",
    "Cheetah",
    "Fissure",
    "Leopard",
    "Gray Wolf (Bronze)",
    "Decisive Strike",
    "Indian Gavial",
    "Alien Egg B",
    "Smalltooth Sawfish",
    "Giant UFO",
    "Strategic Mind",
    "Goblin Shark",
    "Alien Egg C",
    "Black Panther",
    "Shining Blade",
    "Giant Meteor (Bronze)",
    "Time of Miracles",
    "Golden Eagle",
    "Magma Inferno",
    "Electric Ray",
    "Turnaround Blow",
    "Brown Bear",
    "Polar Bear (Silver)",
    "Lava Flow",
    "Asiatic Black Bear",
    "All Out Power",
    "Manta Ray",
    "Earthquake",
    "Blue the Young Shark (Bronze)",
    "Hidden Strength",
    "Andean Condor",
    "Pure Soul",
    "Side Striped Jackal",
    "Lightning",
    "Sawshark",
    "Brown Bear",
  ],
  B: [
    "Anaconda",
    "Lightning",
    "Sawshark",
    "Forbidden Arts",
    "Leo the Lion Cub (Bronze)",
    "Call of the Wild",
    "Earthquake",
    "Brown Bear",
    "Manta Ray",
    "Soul of a King",
    "Indian Gavial",
    "Volcanic Chain",
    "Hidden Power (Bronze)",
    "Nasty Surprise",
    "Smalltooth Sawfish",
    "Burning Spirit",
    "Goblin Shark",
    "Giant UFO",
    "Alien Egg A (Bronze)",
    "Golden Eagle",
    "Wheels of Fate",
    "Andean Condor",
    "Alien Egg B",
    "Gray Wolf (Bronze)",
    "Furious Charge",
    "Side Striped Jackal",
    "Focus Charge",
    "Coral Snake",
    "Great Horned Owl",
    "Lightning Speed",
    "Snow Leopard",
    "Lava Flow",
    "Arctic Training (Bronze)",
    "Rattlesnake",
    "Alien Egg C",
    "Leopard",
    "Virtuous Skies (Silver)",
    "Cheetah",
    "Pure Soul",
    "African Wild Dog",
    "Great Lightning",
    "Asiatic Black Bear",
    "Giant Meteor (Bronze)",
    "Wheels of Fate",
    "Electric Ray",
    "Time of Miracles",
    "Super Lightning",
    "Manta Ray",
    "Magma Inferno",
    "Decisive Strike",
    "Peregrine Falcon",
    "Giant UFO",
    "Coral Snake",
    "Call of the Wild",
    "Anaconda",
    "Ice Meteor (Bronze)",
    "Insatiable Appetite",
    "Rattlesnake",
    "Alien Egg B",
    "Snow Leopard",
    "Early Riser",
    "Polar Bear (Silver)",
    "Great Horned Owl",
    "Volcanic Chain",
    "African Wild Dog",
    "Unbreakable Spirit",
    "Cheetah",
    "Giant Melon",
    "Icarus the Young Eagle (Bronze)",
    "Lightning Speed",
    "Leopard",
    "Shining Blade",
    "Indian Gavial",
    "Smalltooth Sawfish",
    "Alien Egg C",
    "Goblin Shark",
    "Black Panther",
    "All Out Power",
    "Golden Eagle",
    "Electric Ray",
    "Victory Power (Bronze)",
    "Black Panther",
    "Super Lightning",
    "Brown Bear",
    "Asiatic Black Bear",
    "Giant Meteor (Bronze)",
    "Turnaround Blow",
    "Manta Ray",
    "Giant Melon",
    "Andean Condor",
    "Pure Soul",
    "Giant Panda (Bronze)",
    "Magma Inferno",
    "Side Striped Jackal",
    "Sawshark",
    "Hidden Strength",
    "Peregrine Falcon",
    "Fissure",
    "Coral Snake",
    "Burning Spirit",
    "Turnaround Blow",
    "Black Panther",
    "Giant UFO",
    "Anaconda",
    "Leadership (Bronze)",
    "Time of Miracles",
    "Sawshark",
    "Lava Flow",
    "Brown Bear",
    "Hidden Strength",
    "Peregrine Falcon",
    "Alien Egg C",
    "Crashing Moon (Silver)",
    "Indian Gavial",
    "Furious Charge",
    "Smalltooth Sawfish",
    "Super Lightning",
    "Goblin Shark",
    "Blue the Young Shark (Bronze)",
    "Anaconda",
    "Golden Eagle",
    "Lightning",
    "Andean Condor",
    "Great Lightning",
    "Decisive Strike",
    "Side Striped Jackal",
    "Fissure",
    "Black Panther",
    "Insatiable Appetite",
    "Alien Egg A (Bronze)",
    "Golden Eagle",
    "Great Horned Owl",
    "Snow Leopard",
    "Giant Melon",
    "Nasty Surprise",
    "Rattlesnake",
    "Great White Shark (Gold)",
    "Earthquake",
    "Leopard",
    "Ultimate Power",
    "Cheetah",
    "Volcanic Chain",
    "Nile Crocodile (Bronze)",
    "Forbidden Arts",
    "African Wild Dog",
    "Strategic Mind",
    "Asiatic Black Bear",
    "Alien Egg B",
    "Rattlesnake",
    "Magma Inferno",
  ],
  C: [
    "Manta Ray",
    "Giant Melon",
    "Black Panther",
    "All Out Power",
    "Anaconda",
    "Ice Meteor (Bronze)",
    "Nasty Surprise",
    "Sawshark",
    "Alien Egg C",
    "Brown Bear",
    "Hidden Strength",
    "Bald Eagle (Gold)",
    "Peregrine Falcon",
    "Volcanic Chain",
    "Indian Gavial",
    "Shining Blade",
    "Smalltooth Sawfish",
    "Alien Egg B",
    "Icarus the Young Eagle (Bronze)",
    "Great Lightning",
    "Goblin Shark",
    "Call of the Wild",
    "Golden Eagle",
    "Andean Condor",
    "Giant UFO",
    "Side Striped Jackal",
    "Coral Snake",
    "Early Riser",
    "Great Horned Owl",
    "Snow Leopard",
    "Victory Power (Bronze)",
    "Anaconda",
    "Super Lightning",
    "Rattlesnake",
    "Leopard",
    "Meteor Shower (Silver)",
    "Turnaround Blow",
    "Cheetah",
    "Magma Inferno",
    "African Wild Dog",
    "Pure Soul",
    "Giant Panda (Bronze)",
    "Giant Melon",
    "Asiatic Black Bear",
    "Electric Ray",
    "Electric Ray",
    "Peregrine Falcon",
    "Great Lightning",
    "Black Panther",
    "Lava Flow",
    "Insatiable Appetite",
    "Coral Snake",
    "Great Lightning",
    "Anaconda",
    "Leadership (Bronze)",
    "Nasty Surprise",
    "Rattlesnake",
    "Super Lightning",
    "Snow Leopard",
    "Early Riser",
    "Great Horned Owl",
    "Volcanic Chain",
    "Virtuous Skies (Silver)",
    "African Wild Dog",
    "Furious Charge",
    "Cheetah",
    "Fissure",
    "Leopard",
    "Gray Wolf (Bronze)",
    "Soul of a King",
    "Indian Gavial",
    "Alien Egg B",
    "Smalltooth Sawfish",
    "Giant UFO",
    "Strategic Mind",
    "Goblin Shark",
    "Alien Egg C",
    "Black Panther",
    "Shining Blade",
    "Alien Egg A (Bronze)",
    "Hidden Strength",
    "Golden Eagle",
    "Magma Inferno",
    "Electric Ray",
    "Turnaround Blow",
    "Brown Bear",
    "African Elephant (Silver)",
    "Lava Flow",
    "Asiatic Black Bear",
    "Ultimate Power",
    "Manta Ray",
    "Earthquake",
    "Blue the Young Shark (Bronze)",
    "Focus Charge",
    "Andean Condor",
    "Decisive Strike",
    "Side Striped Jackal",
    "Lightning",
    "Sawshark",
    "Golden Eagle",
    "Anaconda",
    "Lightning",
    "Sawshark",
    "Golden Eagle",
    "Anaconda",
    "Lightning",
    "Sawshark",
    "Forbidden Arts",
    "Leo the Lion Cub (Bronze)",
    "Unbreakable Spirit",
    "Earthquake",
    "Brown Bear",
    "Peregrine Falcon",
    "Soul of a King",
    "Volcanic Chain",
    "Indian Gavial",
    "Hidden Power (Bronze)",
    "Brown Bear",
    "Smalltooth Sawfish",
    "Burning Spirit",
    "Goblin Shark",
    "Giant UFO",
    "Indian Cobra (Silver)",
    "Golden Eagle",
    "Wheels of Fate",
    "Andean Condor",
    "Alien Egg B",
    "Nile Crocodile (Bronze)",
    "All Out Power",
    "Side Striped Jackal",
    "Focus Charge",
    "Coral Snake",
    "Great Horned Owl",
    "Lightning Speed",
    "Snow Leopard",
    "Lava Flow",
    "Arctic Training (Bronze)",
    "Rattlesnake",
    "Alien Egg C",
    "Leopard",
    "Ice Meteor (Bronze)",
    "Cheetah",
    "Pure Soul",
    "African Wild Dog",
    "Fissure",
    "Strategic Mind",
    "Giant Melon",
    "Manta Ray",
    "Super Lightning",
    "Time of Miracles",
  ],
  D: [
    "Turnaround Blow",
    "Black Panther",
    "Giant UFO",
    "Anaconda",
    "Arctic Training (Bronze)",
    "Focus Charge",
    "Sawshark",
    "Lava Flow",
    "Brown Bear",
    "Hidden Strength",
    "Peregrine Falcon",
    "Alien Egg C",
    "Bengal Tiger (Gold)",
    "Indian Gavial",
    "Wheels of Fate",
    "Smalltooth Sawfish",
    "Super Lightning",
    "Goblin Shark",
    "Blue the Young Shark (Bronze)",
    "Black Panther",
    "Golden Eagle",
    "Lightning",
    "Andean Condor",
    "Great Lightning",
    "Decisive Strike",
    "Side Striped Jackal",
    "Fissure",
    "Coral Snake",
    "Soul of a King",
    "Alien Egg A (Bronze)",
    "Brown Bear",
    "Great Horned Owl",
    "Giant Melon",
    "Snow Leopard",
    "Nasty Surprise",
    "Rattlesnake",
    "Indian Cobra (Silver)",
    "Earthquake",
    "Leopard",
    "Ultimate Power",
    "Cheetah",
    "Volcanic Chain",
    "Nile Crocodile (Bronze)",
    "Unbreakable Spirit",
    "African Wild Dog",
    "Strategic Mind",
    "Asiatic Black Bear",
    "Alien Egg B",
    "Electric Ray",
    "Wheels of Fate",
    "Manta Ray",
    "Giant Melon",
    "Black Panther",
    "All Out Power",
    "Anaconda",
    "Ice Meteor (Bronze)",
    "Turnaround Blow",
    "Sawshark",
    "Alien Egg C",
    "Brown Bear",
    "Hidden Strength",
    "Ocean Power (Silver)",
    "Peregrine Falcon",
    "Volcanic Chain",
    "Indian Gavial",
    "Shining Blade",
    "Smalltooth Sawfish",
    "Alien Egg B",
    "Leo the Lion Cub (Bronze)",
    "Pure Soul",
    "Goblin Shark",
    "Forbidden Arts",
    "Golden Eagle",
    "Andean Condor",
    "Giant UFO",
    "Side Striped Jackal",
    "Coral Snake",
    "Early Riser",
    "Great Horned Owl",
    "Snow Leopard",
    "Victory Power (Bronze)",
    "Golden Eagle",
    "Super Lightning",
    "Rattlesnake",
    "Leopard",
    "Giant Meteor (Bronze)",
    "Turnaround Blow",
    "Cheetah",
    "Magma Inferno",
    "African Wild Dog",
    "Burning Spirit",
    "Giant Panda (Bronze)",
    "Giant Melon",
    "Asiatic Black Bear",
    "Electric Ray",
    "Unbreakable Spirit",
    "Manta Ray",
    "Great Lightning",
    "Black Panther",
    "Fissure",
    "Anaconda",
    "Giant UFO",
    "Rattlesnake",
    "Focus Charge",
    "Icarus the Young Eagle (Bronze)",
    "Ultimate Power",
    "Alien Egg B",
    "Snow Leopard",
    "Great Horned Owl",
    "Time of Miracles",
    "African Wild Dog",
    "Alien Egg C",
    "Hidden Power (Bronze)",
    "Forbidden Arts",
    "Cheetah",
    "Lightning Speed",
    "Leopard",
    "Lava Flow",
    "Ice Meteor (Bronze)",
    "Indian Gavial",
    "Pure Soul",
    "Smalltooth Sawfish",
    "Lightning",
    "Gray Wolf (Bronze)",
    "Burning Spirit",
    "Goblin Shark",
    "Pure Soul",
    "Coral Snake",
    "Golden Eagle",
    "Insatiable Appetite",
    "Electric Ray",
    "Super Lightning",
    "Leadership (Bronze)",
    "Brown Bear",
    "Earthquake",
    "Asiatic Black Bear",
    "Crashing Moon (Silver)",
    "Manta Ray",
    "Call of the Wild",
    "Andean Condor",
    "Magma Inferno",
    "Side Striped Jackal",
    "Alien Egg A (Bronze)",
    "Strategic Mind",
    "Sawshark",
    "Furious Charge",
    "Fissure",
    "Peregrine Falcon",
    "Volcanic Chain",
    "Early Riser",
  ],
};
