export const decks = {
  A: [
    "Goblin Shark",
    "Pacific Divide",
    "Anaconda",
    "Great Lightning",
    "Feel for Battle",
    "Leo the Lion Cub (Bronze)",
    "Power Grab",
    "Flash of Light",
    "Turnaround Blow",
    "Asiatic Black Bear",
    "Peregrine Falcon",
    "Hammerhead Shark (Silver)",
    "Lightning Speed",
    "Earthquake",
    "Hippo Barry",
    "Andean Condor",
    "Burning Spirit",
    "Leopard",
    "Joe the Tiger (Bronze)",
    "African Wild Dog",
    "Dark Scorpion",
    "Soul of a King",
    "Manta Ray",
    "Goblin Shark",
    "Ultimate Power",
    "Great Horned Owl",
    "Lava Flow",
    "Anaconda",
    "Hidden Strength",
    "Smalltooth Sawfish",
    "Nile Crocodile (Bronze)",
    "Soul of a King",
    "Burning Spirit",
    "Side-Striped Jackal",
    "Alien Egg C",
    "Blue the Young Shark (Bronze)",
    "Great Lightning",
    "Giant Melon",
    "Focus Charge",
    "Golden Eagle",
    "Indian Gavial",
    "Giant Panda (Bronze)",
    "Flash of Light",
    "Manta Ray",
    "Hippo Harry",
    "Pure Soul",
    "Giant UFO",
    "Rattlesnake the 2nd",
    "Pacific Divide",
    "Fissure",
    "Dream of Victory",
    "Smalltooth Sawfish",
    "Soul of a King",
    "Electric Ray",
    "Indian Rhinoceros (Bronze)",
    "Call of the wild",
    "Brown Bear",
    "Feel for Battle",
    "Goblin Shark",
    "Great Horned Owl",
    "Hippo Barry",
    "Dark Scorpion",
    "Hidden Power (Bronze)",
    "Florida Bark Scorpion",
    "Time of Miracles",
    "Side-Striped Jackal",
    "Alien Egg B",
    "Leopard",
    "Hippo Larry (Silver)",
    "Super Lightning",
    "Peregrine Falcon",
    "Andean Condor",
    "Anaconda",
    "Alien Egg A (Bronze)",
    "Lightning Speed",
    "Smalltooth Sawfish",
    "Indian Gavial",
    "Dream of Victory",
    "Coral Snake the 2nd",
    "Spirit of Gaia",
    "Alien Egg C",
    "Pacific Divide",
    "Ice Meteor (Bronze)",
    "Flash of Light",
    "Ultimate Power",
    "Cheetah",
    "Lion (Gold)",
    "Rattlesnake the 2nd",
    "Snow Leopard",
    "Turnaround Blow",
    "Burning Spirit",
    "Magma Inferno",
    "Hidden Power (Bronze)",
    "Brown Bear",
    "Goblin Shark",
    "Great Lightning",
    "Earthquake",
    "Giant UFO",
    "Coral Snake, the 2nd",
    "Power Grab",
    "Call of the wild",
    "Soul of a King",
    "Giant Melon",
    "Electric Ray",
    "Nile Crocodile (Bronze)",
    "Dark Scorpion",
    "Lightning Speed",
    "Flash of Light",
    "Manta Ray",
    "Leopard",
    "African Wild Dog",
    "Hippo Barry",
    "Meteor Shower (Silver)",
    "Side-Striped Jackal",
    "Florida Bark Scorpion",
    "Peregrine Falcon",
    "Spirit of Gaia",
    "Great Horned Owl",
    "Giant Panda (Bronze)",
    "Snow Leopard",
    "Super Lightning",
    "Goblin Shark",
    "Pacific Divide",
    "Time of Miracles",
    "Feel for Battle",
    "Brown Bear",
    "Golden Eagle",
    "Lightning Speed",
    "Indian Gavial",
    "Sea Lord Insignia (Bronze)",
    "Hidden Strength",
    "Lava Flow",
    "Asiatic Black Bear",
    "Electric Ray",
    "Great Lightning",
    "Goblin Shark",
    "Secret Moonlight (Silver)",
    "Dream of Victory",
    "Earthquake",
    "Call of the wild",
    "Ultimate Power",
    "Side-Striped Jackal",
    "Giant Meteor (Bronze)",
    "Hippo Harry",
    "Alien Egg C",
    "Power Grab",
    "Dark Scorpion",
    "Great Horned Owl",
    "Soul of a King",
    "Rattlesnake the 2nd",
  ],
  B: [
    "Magma Inferno",
    "Manta Ray",
    "Soul of a King",
    "Pacific Divide",
    "King Insignia (Bronze)",
    "Side-Striped Jackal",
    "Pure Soul",
    "Indian Gavial",
    "Dark Scorpion",
    "Lightning Speed",
    "Pacific Divide",
    "Florida Bark Scorpion",
    "Ice Meteor (Bronze)",
    "Asiatic Black Bear",
    "Sawshark",
    "Manta Ray",
    "Focus Charge",
    "Manta Ray",
    "Alien Egg D (Bronze)",
    "Pacific Divide",
    "Fissure",
    "Anaconda",
    "Peregrine Falcon",
    "Nile Crocodile (Bronze)",
    "African Wild Dog",
    "Andean Condor",
    "Burning Spirit",
    "Leopard",
    "Cheetah",
    "Soul of a King",
    "Snow Leopard",
    "Alien Egg B",
    "Kid the Tiger (Bronze)",
    "Snow Leopard",
    "Indian Gavial",
    "Coral Snake, the 2nd",
    "African Elephant (Silver)",
    "Golden Eagle",
    "Super Lightning",
    "Side-Striped Jackal",
    "Earthquake",
    "Fissure",
    "Alien Egg A (Bronze)",
    "Golden Eagle",
    "Ultimate Power",
    "Great Horned Owl",
    "Call of the wild",
    "Spirit of Gaia",
    "Flash of Light",
    "Side-Striped Jackal",
    "Great Horned Owl",
    "Goblin Shark",
    "Great Lightning",
    "Pacific Divide",
    "Hippo Barry",
    "Hidden Power (Bronze)",
    "Spirit of Gaia",
    "Florida Bark Scorpion",
    "Pure Soul",
    "Electric Ray",
    "Golden Eagle",
    "Mighty Fighter (Silver)",
    "Call of the wild",
    "Great Lightning",
    "Power Grab",
    "Soul of a King",
    "Electric Ray",
    "Dream of Victory",
    "Leadership (Bronze)",
    "Feel for Battle",
    "Leopard",
    "Lightning Speed",
    "Alien Egg C",
    "Giant UFO",
    "Leopard",
    "Peregrine Falcon",
    "Flash of Light",
    "Call of the wild",
    "Giant Melon",
    "Lava Flow",
    "Giant Panda (Bronze)",
    "Dream of Victory",
    "Florida Bark Scorpion",
    "Feel for Battle",
    "Super Lightning",
    "Leo the Lion Cub (Bronze)",
    "Indian Gavial",
    "Feel for Battle",
    "Turnaround Blow",
    "Goblin Shark",
    "Hippo Harry",
    "Blue the Young Shark (Bronze)",
    "Rattlesnake the 2nd",
    "Call of the wild",
    "Coral Snake the 2nd",
    "Dream of Victory",
    "Indian Gavial",
    "Focus Charge",
    "Giant UFO",
    "Anaconda",
    "Hippo Harry",
    "Soul of a King",
    "Peregrine Falcon",
    "Super Lightning",
    "Alien Egg A (Bronze)",
    "Alien Egg C",
    "Dark Scorpion",
    "Ultimate Power",
    "Coral Snake the 2nd",
    "Rattlesnake the 2nd",
    "Golden Eagle",
    "Goblin Shark",
    "Black Hole (Silver)",
    "Brown Bear",
    "Smalltooth Sawfish",
    "Turnaround Blow",
    "Time of Miracles",
    "Dark Scorpion",
    "Sea Lord Insignia (Bronze)",
    "Time of Miracles",
    "Electric Ray",
    "Great Lightning",
    "Manta Ray",
    "Brown Bear",
    "Power Grab",
    "Goblin Shark",
    "Ultimate Power",
    "Focus Charge",
    "Brown Bear",
    "Alien Egg D (Bronze)",
    "Goblin Shark",
    "Hippo Harry",
    "Power Grab",
    "Call of the wild",
    "Smalltooth Sawfish",
    "Goblin Shark",
    "Red Scorpion (Gold)",
    "Black Panther",
    "Dark Scorpion",
    "Great Lightning",
    "Earthquake",
    "Andean Condor",
    "Nile Crocodile (Bronze)",
    "Giant Melon",
    "Lava Flow",
    "Spirit of Gaia",
    "Giant Melon",
    "Side-Striped Jackal",
    "Great Horned Owl",
    "African Wild Dog",
  ],
  C: [
    "Focus Charge",
    "Leopard",
    "Snow Leopard",
    "Rattlesnake the 2nd",
    "Ultimate Power",
    "Giant Panda (Bronze)",
    "Dark Scorpion",
    "Feel for Battle",
    "Golden Eagle",
    "Flash of Light",
    "Lightning Speed",
    "Bald Eagle (Gold)",
    "Rattlesnake the 2nd",
    "Lava Flow",
    "Coral Snake the 2nd",
    "Super Lightning",
    "Peregrine Falcon",
    "Cheetah",
    "Kid the Tiger (Bronze)",
    "Flash of Light",
    "Spirit of Gaia",
    "Great Horned Owl",
    "Goblin Shark",
    "Side-Striped Jackal",
    "Cheetah",
    "Focus Charge",
    "Giant Melon",
    "Giant UFO",
    "Soul of a King",
    "Hippo Barry",
    "Hidden Power (Bronze)",
    "Snow Leopard",
    "Golden Eagle",
    "Magma Inferno",
    "Leopard",
    "Crashing Moon (Silver)",
    "Dark Scorpion",
    "Black Panther",
    "Great Horned Owl",
    "Golden Eagle",
    "Coral Snake the 2nd",
    "Blue the Young Shark (Bronze)",
    "Alien Egg B",
    "Electric Ray",
    "Alien Egg C",
    "Hidden Strength",
    "Goblin Shark",
    "Lightning Speed",
    "Ultimate Power",
    "Flash of Light",
    "Dark Scorpion",
    "Electric Ray",
    "Brown Bear",
    "Pacific Divide",
    "Leo the Lion Cub (Bronze)",
    "Coral Snake the 2nd",
    "Andean Condor",
    "Power Grab",
    "Power Grab",
    "Flash of Light",
    "Dream of Victory",
    "Alien Egg C",
    "Mighty Fighter (Silver)",
    "Time of Miracles",
    "Goblin Shark",
    "Giant Melon",
    "Hippo Harry",
    "Anaconda",
    "Alien Egg D (Bronze)",
    "Dream of Victory",
    "Great Lightning",
    "Great Horned Owl",
    "Lightning Speed",
    "African Wild Dog",
    "Goblin Shark",
    "Indian Gavial",
    "Manta Ray",
    "Pure Soul",
    "Pacific Divide",
    "Alien Egg A (Bronze)",
    "Power Grab",
    "Hippo Harry",
    "Sawshark",
    "Peregrine Falcon",
    "Golden Eagle",
    "Smalltooth Sawfish",
    "Hammerhead Shark (Silver)",
    "Pacific Divide",
    "Manta Ray",
    "Soul of a King",
    "Hippo Barry",
    "Time of Miracles",
    "Kid the Tiger (Bronze)",
    "Soul of a King",
    "Goblin Shark",
    "Dream of Victory",
    "Great Lightning",
    "Cheetah",
    "Rattlesnake the 2nd",
    "Florida Bark Scorpion",
    "Side-Striped Jackal",
    "Spirit of Gaia",
    "Great Horned Owl",
    "Indian Gavial",
    "Manta Ray",
    "Pure Soul",
    "Smalltooth Sawfish",
    "Leopard",
    "Giant Meteor (Bronze)",
    "Spirit of Gaia",
    "Manta Ray",
    "Peregrine Falcon",
    "Great Lightning",
    "Flash of Light",
    "Soul of a King",
    "Hidden Strength",
    "Indian Rhinoceros (Bronze)",
    "Alien Egg B",
    "Call of the wild",
    "Anaconda",
    "Focus Charge",
    "Lava Flow",
    "Secret Moonlight (Silver)",
    "Alien Egg C",
    "Ultimate Power",
    "Brown Bear",
    "Call of the wild",
    "Leadership (Bronze)",
    "Anaconda",
    "Feel for Battle",
    "Super Lightning",
    "Smalltooth Sawfish",
    "Florida Bark Scorpion",
    "Side-Striped Jackal",
    "Call of the wild",
    "Pacific Divide",
    "Fissure",
    "King Insignia (Bronze)",
    "Peregrine Falcon",
    "Side-Striped Jackal",
    "Giant UFO",
    "Andean Condor",
    "Earthquake",
    "Goblin Shark",
    "Hippo Barry",
    "African Wild Dog",
    "Black Panther",
    "Super Lightning",
    "Hippo Harry",
    "Indian Gavial",
  ],
  D: [
    "Soul of a King",
    "Coral Snake the 2nd",
    "Peregrine Falcon",
    "Flash of Light",
    "Hippo Harry",
    "Joe the Tiger (Bronze)",
    "Dark Scorpion",
    "Ultimate Power",
    "Power Grab",
    "Great Lightning",
    "Leopard",
    "Electric Ray",
    "Bengal Tiger (Gold)",
    "Alien Egg B",
    "Pacific Divide",
    "Super Lightning",
    "Spirit of Gaia",
    "Call of the wild",
    "Indian Rhinoceros (Bronze)",
    "Cheetah",
    "Focus Charge",
    "Dream of Victory",
    "Smalltooth Sawfish",
    "Golden Eagle",
    "Earthquake",
    "Time of Miracles",
    "Florida Bark Scorpion",
    "Pure Soul",
    "Hippo Barry",
    "Leadership (Bronze)",
    "Goblin Shark",
    "Burning Spirit",
    "Feel for Battle",
    "Snow Leopard",
    "Manta Ray",
    "Anaconda",
    "Hammerhead Shark (Silver)",
    "Pacific Divide",
    "Flash of Light",
    "Giant UFO",
    "Indian Gavial",
    "Lightning Speed",
    "Sea Lord Insignia (Bronze)",
    "Dream of Victory",
    "Side-Striped Jackal",
    "Electric Ray",
    "Goblin Shark",
    "Focus Charge",
    "Brown Bear",
    "Alien Egg C",
    "Feel for Battle",
    "Golden Eagle",
    "Hippo Barry",
    "Giant Melon",
    "Rattlesnake the 2nd",
    "Alien Egg D (Bronze)",
    "Call of the wild",
    "Snow Leopard",
    "Cheetah",
    "Super Lightning",
    "Earthquake",
    "Crashing Moon (Silver)",
    "Peregrine Falcon",
    "Dark Scorpion",
    "Manta Ray",
    "Goblin Shark",
    "Time of Miracles",
    "Coral Snake the 2nd",
    "Ice Meteor (Bronze)",
    "Hippo Harry",
    "Ultimate Power",
    "Leopard",
    "Turnaround Blow",
    "Anaconda",
    "Alien Egg C",
    "Great Horned Owl",
    "Focus Charge",
    "Power Grab",
    "Flash of Light",
    "Andean Condor",
    "Giant Panda (Bronze)",
    "Florida Bark Scorpion",
    "Soul of a King",
    "Great Lightning",
    "Pure Soul",
    "Golden Eagle",
    "Side-Striped Jackal",
    "Flash of Light",
    "Dream of Victory",
    "Anaconda",
    "Joe the Tiger (Bronze)",
    "Call of the wild",
    "Indian Gavial",
    "Coral Snake the 2nd",
    "Feel for Battle",
    "Smalltooth Sawfish",
    "Manta Ray",
    "Alien Egg B",
    "Rattlesnake the 2nd",
    "Earthquake",
    "Nile Crocodile (Bronze)",
    "Brown Bear",
    "African Wild Dog",
    "Cheetah",
    "Electric Ray",
    "Goblin Shark",
    "Lightning Speed",
    "Side-Striped Jackal",
    "Spirit of Gaia",
    "Giant Melon",
    "Great Horned Owl",
    "Alien Egg C",
    "Alien Egg A (Bronze)",
    "Soul of a King",
    "Peregrine Falcon",
    "Golden Eagle",
    "Giant Melon",
    "Hippo Harry",
    "King Insignia (Bronze)",
    "Turnaround Blow",
    "Snow Leopard",
    "Focus Charge",
    "Goblin Shark",
    "Giant Panda (Bronze)",
    "Dream of Victory",
    "Anaconda",
    "Coral Snake the 2nd",
    "Smalltooth Sawfish",
    "Electric Ray",
    "Flash of Light",
    "Florida Bark Scorpion",
    "Great Lightning",
    "Blue the Young Shark (Bronze)",
    "Dark Scorpion",
    "Hidden Strength",
    "Time of Miracles",
    "Hippo Larry (Silver)",
    "Burning Spirit",
    "Feel for Battle",
    "Giant UFO",
    "Indian Gavial",
    "Ice Meteor (Bronze)",
    "Sawshark",
    "Black Panther",
    "Lightning Speed",
    "Snow Leopard",
    "Manta Ray",
    "Lava Flow",
    "Magma Inferno",
    "Andean Condor",
  ],
};
