name: Release Automation

on:
  push:
    tags:
      - 'v*'  # Only trigger when pushing a tag like v1.2.3

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
